export const CHAT_USER = 'CHAT_USER';
export const IS_AUTHENTICATE = 'IS_AUTHENTICATE';
export const USER_INFO = 'USER_INFO';
export const ENABLE_CONTACT = 'ENABLE_CONTACT';
export const SET_TEMP_CONTACT = 'SET_TEMP_CONTACT';
export const SET_CONTACT = 'SET_CONTACT';